title: Tokenz (Obsidian plugin)
description: Smileys, emoticons and any kind of short codes you can imagine
show_downloads: true
google_analytics: GTM-T47R9MX8
theme: jekyll-theme-leap-day
google_site_verification: dSXyPF8wjboE3nlpS89FWsrFjURklLwimxdmIloilrk
